version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
    ignore:
      - dependency-name: rails
        versions:
          - ">= 6.1.a, < 6.2"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
    ignore:
      - dependency-name: core-js
        versions:
          - 3.10.2

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
