name: Verify
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: synka_test
          POSTGRES_PASSWORD: "password"
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: "yarn"

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: myapp
        run: |
          bin/rails db:setup

      - name: Run tests
        # env:
        #   BLINKA_REPORT: true
        #   BLINKA_BRANCH: main
        #   BLINKA_REPOSITORY: davidwessman/synka
        #   BLINKA_TEAM_ID: ${{ secrets.BLINKA_TEAM_ID }}
        #   BLINKA_TEAM_SECRET: ${{ secrets.BLINKA_TEAM_SECRET }}
        run: bundle exec rails test:all
